#include "hal_data.h"
#include "debug_uart/bsp_debug_uart.h"
#include "iic/iic.h"
#include "iic/imu.h"
#include "flash/flash.h"
#include "gpt/gpt.h"
#include "key/key.h"
#include "lcd/lcd.h"
#include "display/display.h"
#include "power/power.h"
#include "adc/adc.h"
#include "param/param.h"
#include "command/command.h"
#include <stdio.h>
#include <string.h>

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    R_BSP_PinAccessEnable();

    /* LATCH 上电保持：P301 拉高开机 */
    power_latch_init();

    /* UART 初始化 */
    Debug_UART9_Init();

    /* I2C 初始化 */
    i2c_master_init();

    /* IMU 识别与初始化 (IIM-42351 / ICM-40608 / LSM6DSOTR) */
    imu_init();

    /* Flash 初始化 */
    flash_init();

    /* 参数存储: 读回配置/统计, 首次上电写入默认 */
    param_init();

    /* LCD 初始化 (AiP31033E, 硬件 SPI + GPIO A0/CS/RST) */
    lcd_init();

    /* 1ms 心跳定时器启动 (GPT9) */
    gpt_init();

    /* 按键初始化 (SW1~SW4, 高电平触发) */
    key_init();

    /* 电源时序: 先拉高 EN 7V(P914), 延时 10ms, 再拉高 EN 5V(P915) */
    power_seq_init();

    /* ADC 初始化 (buck 7V 电压检测 P014 + 电池电量检测 P015) */
    adc_init();

    /* 自动关机定时器: AGT1 1s, 无操作 60s 后关机 */
    power_autooff_init();

    /* 启动信息打印 */
    uart9_send_blocking("\r\n========================================\r\n");
    uart9_send_blocking("  Hanger LDM V0.1  System Boot\r\n");
    uart9_send_blocking("========================================\r\n");
    uart9_send_blocking("[PWR ] LATCH ON (P301 HIGH)\r\n");
    uart9_send_blocking("[UART] UART9 Init OK\r\n");
    uart9_send_blocking("[I2C ] I2C Init OK\r\n");
    uart9_send_blocking("[FLSH] Flash Init OK\r\n");
    uart9_send_blocking("[LCD ] LCD Init OK\r\n");
    uart9_send_blocking("[TMR ] GPT9 1ms Tick OK\r\n");
    uart9_send_blocking("[ADC ] ADC Init OK\r\n");
    uart9_send_blocking("System init OK\r\n");

    /* ===== UI 状态机上下文 ===== */
    ui_state_t ui;
    char       buf[64];

    /* 初始化状态机到开机初始态并刷屏 */
    ui_state_init(&ui);
    uart9_send_blocking("[LCD ] Display init (icon IDLE, digital OFF)\r\n");

    /* 开机键检测: 仅对开机时按住的键保留「首次忽略」, 未按住的键首次短按立即响应 */
    if (!key_is_pressed(KEY_ID_SW3))
    {
        ui.sw3_first = false;
    }
    if (!key_is_pressed(KEY_ID_SW4))
    {
        ui.sw4_first = false;
    }

    while (1)
    {
        /* AGT1 1s 节拍: 时间统计 (主循环处理, 保持中断短小) */
        if (power_1s_tick_pending())
        {
            param_tick_1s(adc_battery_is_low());
        }

        /* 1ms 任务 */
        if (g_task_flags & TASK_FLAG_1MS)
        {
            gpt_flag_clear(TASK_FLAG_1MS);
            /* TODO: 添加 1ms 任务 */
        }

        /* 10ms 任务 */
        if (g_task_flags & TASK_FLAG_10MS)
        {
            gpt_flag_clear(TASK_FLAG_10MS);
            key_scan();

            /* 串口接收: 统一指令分发 (指令或米值) */
            if (uart9_line_ready())
            {
                char line[32];

                uart9_get_line(line, sizeof(line));
                command_process_line(line, &ui);
            }

            /* 按键事件处理: 映射为 UI 事件并分派给状态机 */
            uint8_t i;
            for (i = 0U; i < KEY_NUM; i++)
            {
                key_event_t ev = key_get_event((key_id_t)i);

                /* 任意按键事件均重置 60s 自动关机倒计时 */
                if (KEY_EVENT_NONE != ev)
                {
                    power_activity();
                }

                if (KEY_EVENT_SHORT_PRESS == ev)
                {
                    /* 记录短按次数 */
                    param_key_event(i, false);

                    /* 按键 ID -> UI 状态机事件 */
                    switch (i)
                    {
                        case KEY_ID_SW1: ui_state_dispatch(&ui, UI_EVT_SW1_SHORT); break;
                        case KEY_ID_SW2: ui_state_dispatch(&ui, UI_EVT_SW2_SHORT); break;
                        case KEY_ID_SW3: ui_state_dispatch(&ui, UI_EVT_SW3_SHORT); break;
                        case KEY_ID_SW4: ui_state_dispatch(&ui, UI_EVT_SW4_SHORT); break;
                        default: break;
                    }

                    sprintf(buf, "[KEY ] SW%u short press (form %u, digital %u, t7 %u)\r\n",
                            (unsigned)(i + 1U), (unsigned)ui.form,
                            (unsigned)ui.digital, (unsigned)ui.t7);
                    uart9_send_blocking(buf);
                }
                else if (KEY_EVENT_LONG_PRESS == ev)
                {
                    /* 记录长按次数 */
                    param_key_event(i, true);

                    sprintf(buf, "[KEY ] SW%u long press\r\n", (unsigned)(i + 1U));
                    uart9_send_blocking(buf);

                    /* SW1/SW2 长按关机 */
                    if ((KEY_ID_SW1 == i) || (KEY_ID_SW2 == i))
                    {
                        param_set_shutdown_reason(SHUTDOWN_MANUAL);
                        param_save();
                        uart9_send_blocking("[PWR] SW1/SW2 long press, power off\r\n");
                        power_off();
                    }
                }
            }
        }

        /* 20ms 任务 */
        if (g_task_flags & TASK_FLAG_20MS)
        {
            gpt_flag_clear(TASK_FLAG_20MS);
            /* TODO: 添加 20ms 任务 */
        }

        /* 50ms 任务 */
        if (g_task_flags & TASK_FLAG_50MS)
        {
            gpt_flag_clear(TASK_FLAG_50MS);
            /* TODO: 添加 50ms 任务 */
        }

        /* 100ms 任务: IMU 方向检测 + ADC 电池检测 */
        if (g_task_flags & TASK_FLAG_100MS)
        {
            gpt_flag_clear(TASK_FLAG_100MS);

            /* IMU 方向检测 */
            int16_t acc[3];
            if (0 == imu_get_acc(acc))
            {
                /* 加速度计 X 轴方向: >=0 正向, <0 反向 */
                direction_t dir = (acc[0] >= 0) ? DIR_REVERSE : DIR_FORWARD;
                ui_state_set_direction(&ui, dir);
            }

            /* ADC 采样: 读 buck 7V + 电池原始值到缓存 (100ms 周期) */
            adc_sample_update();

            /* ADC 电池检测: 更新电量格数 + 低电关机判定 */
            adc_battery_update();
            ui_state_set_battery(&ui, adc_get_battery_level());

            if (adc_battery_need_shutdown())
            {
                static bool handled = false;

                if (!handled)
                {
                    handled = true;
                    /* 记录低电关机原因并写回 Flash (仅触发一次) */
                    param_set_shutdown_reason(SHUTDOWN_LOW_BATT);
                    param_save();
                }

                uart9_send_blocking("[PWR] battery low (<3.0V), power off\r\n");
                power_off();
            }
        }

        /* 1000ms 任务 */
        if (g_task_flags & TASK_FLAG_1000MS)
        {
            gpt_flag_clear(TASK_FLAG_1000MS);

/*             ADC 原始值打印: 电池 + buck 7V (1s 周期)
            sprintf(buf, "[ADC ] battery raw = %u, buck 7V raw = %u\r\n",
                    (unsigned)adc_read_battery_raw(),
                    (unsigned)adc_read_buck_7v_raw());
            uart9_send_blocking(buf);*/

            /* 无操作 60s 自动关机 */
            if (POWER_STATE_OFF_PENDING == power_get_state())
            {
/*                uart9_send_blocking("[PWR ] 60s idle timeout, power off\r\n");
                power_off();*/
            }
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0
        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;
        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */
        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED
        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
